// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: client/v1/client_api.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientService_CreateOrderNewConfig_FullMethodName     = "/vpns.Client.V1.ClientService/CreateOrderNewConfig"
	ClientService_CreateOrderRefreshConfig_FullMethodName = "/vpns.Client.V1.ClientService/CreateOrderRefreshConfig"
	ClientService_GetTariffs_FullMethodName               = "/vpns.Client.V1.ClientService/GetTariffs"
)

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientServiceClient interface {
	CreateOrderNewConfig(ctx context.Context, in *CreateOrderNewConfigRequest, opts ...grpc.CallOption) (*CreateOrderNewConfigResponse, error)
	CreateOrderRefreshConfig(ctx context.Context, in *CreateOrderRefreshConfigRequest, opts ...grpc.CallOption) (*CreateOrderRefreshConfigResponse, error)
	GetTariffs(ctx context.Context, in *GetTariffsRequest, opts ...grpc.CallOption) (*GetTariffsResponse, error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) CreateOrderNewConfig(ctx context.Context, in *CreateOrderNewConfigRequest, opts ...grpc.CallOption) (*CreateOrderNewConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderNewConfigResponse)
	err := c.cc.Invoke(ctx, ClientService_CreateOrderNewConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) CreateOrderRefreshConfig(ctx context.Context, in *CreateOrderRefreshConfigRequest, opts ...grpc.CallOption) (*CreateOrderRefreshConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderRefreshConfigResponse)
	err := c.cc.Invoke(ctx, ClientService_CreateOrderRefreshConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) GetTariffs(ctx context.Context, in *GetTariffsRequest, opts ...grpc.CallOption) (*GetTariffsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTariffsResponse)
	err := c.cc.Invoke(ctx, ClientService_GetTariffs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
// All implementations must embed UnimplementedClientServiceServer
// for forward compatibility.
type ClientServiceServer interface {
	CreateOrderNewConfig(context.Context, *CreateOrderNewConfigRequest) (*CreateOrderNewConfigResponse, error)
	CreateOrderRefreshConfig(context.Context, *CreateOrderRefreshConfigRequest) (*CreateOrderRefreshConfigResponse, error)
	GetTariffs(context.Context, *GetTariffsRequest) (*GetTariffsResponse, error)
	mustEmbedUnimplementedClientServiceServer()
}

// UnimplementedClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientServiceServer struct{}

func (UnimplementedClientServiceServer) CreateOrderNewConfig(context.Context, *CreateOrderNewConfigRequest) (*CreateOrderNewConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrderNewConfig not implemented")
}
func (UnimplementedClientServiceServer) CreateOrderRefreshConfig(context.Context, *CreateOrderRefreshConfigRequest) (*CreateOrderRefreshConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrderRefreshConfig not implemented")
}
func (UnimplementedClientServiceServer) GetTariffs(context.Context, *GetTariffsRequest) (*GetTariffsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTariffs not implemented")
}
func (UnimplementedClientServiceServer) mustEmbedUnimplementedClientServiceServer() {}
func (UnimplementedClientServiceServer) testEmbeddedByValue()                       {}

// UnsafeClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServiceServer will
// result in compilation errors.
type UnsafeClientServiceServer interface {
	mustEmbedUnimplementedClientServiceServer()
}

func RegisterClientServiceServer(s grpc.ServiceRegistrar, srv ClientServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientService_ServiceDesc, srv)
}

func _ClientService_CreateOrderNewConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderNewConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).CreateOrderNewConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_CreateOrderNewConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).CreateOrderNewConfig(ctx, req.(*CreateOrderNewConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_CreateOrderRefreshConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRefreshConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).CreateOrderRefreshConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_CreateOrderRefreshConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).CreateOrderRefreshConfig(ctx, req.(*CreateOrderRefreshConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_GetTariffs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTariffsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetTariffs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_GetTariffs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetTariffs(ctx, req.(*GetTariffsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientService_ServiceDesc is the grpc.ServiceDesc for ClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vpns.Client.V1.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrderNewConfig",
			Handler:    _ClientService_CreateOrderNewConfig_Handler,
		},
		{
			MethodName: "CreateOrderRefreshConfig",
			Handler:    _ClientService_CreateOrderRefreshConfig_Handler,
		},
		{
			MethodName: "GetTariffs",
			Handler:    _ClientService_GetTariffs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client/v1/client_api.proto",
}
