// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: client/v1/client_api.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderType int32

const (
	OrderType_OrderTypeUnspecified OrderType = 0
	OrderType_OrderTypeCreate      OrderType = 1
	OrderType_OrderTypeRefresh     OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "OrderTypeUnspecified",
		1: "OrderTypeCreate",
		2: "OrderTypeRefresh",
	}
	OrderType_value = map[string]int32{
		"OrderTypeUnspecified": 0,
		"OrderTypeCreate":      1,
		"OrderTypeRefresh":     2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v1_client_api_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_client_v1_client_api_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_client_v1_client_api_proto_rawDescGZIP(), []int{0}
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderType     OrderType              `protobuf:"varint,1,opt,name=OrderType,proto3,enum=vpns.Client.V1.OrderType" json:"OrderType,omitempty"`
	TariffID      int64                  `protobuf:"varint,2,opt,name=TariffID,proto3" json:"TariffID,omitempty"`
	ClientID      string                 `protobuf:"bytes,3,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_client_v1_client_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_OrderTypeUnspecified
}

func (x *CreateOrderRequest) GetTariffID() int64 {
	if x != nil {
		return x.TariffID
	}
	return 0
}

func (x *CreateOrderRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_client_v1_client_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

type Tariff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TariffID      int64                  `protobuf:"varint,1,opt,name=TariffID,proto3" json:"TariffID,omitempty"` // Add other Tariff fields as needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tariff) Reset() {
	*x = Tariff{}
	mi := &file_client_v1_client_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tariff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tariff) ProtoMessage() {}

func (x *Tariff) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tariff.ProtoReflect.Descriptor instead.
func (*Tariff) Descriptor() ([]byte, []int) {
	return file_client_v1_client_api_proto_rawDescGZIP(), []int{2}
}

func (x *Tariff) GetTariffID() int64 {
	if x != nil {
		return x.TariffID
	}
	return 0
}

var File_client_v1_client_api_proto protoreflect.FileDescriptor

const file_client_v1_client_api_proto_rawDesc = "" +
	"\n" +
	"\x1aclient/v1/client_api.proto\x12\x0evpns.Client.V1\"\x85\x01\n" +
	"\x12CreateOrderRequest\x127\n" +
	"\tOrderType\x18\x01 \x01(\x0e2\x19.vpns.Client.V1.OrderTypeR\tOrderType\x12\x1a\n" +
	"\bTariffID\x18\x02 \x01(\x03R\bTariffID\x12\x1a\n" +
	"\bClientID\x18\x03 \x01(\tR\bClientID\"/\n" +
	"\x13CreateOrderResponse\x12\x18\n" +
	"\aOrderID\x18\x01 \x01(\tR\aOrderID\"$\n" +
	"\x06Tariff\x12\x1a\n" +
	"\bTariffID\x18\x01 \x01(\x03R\bTariffID*P\n" +
	"\tOrderType\x12\x18\n" +
	"\x14OrderTypeUnspecified\x10\x00\x12\x13\n" +
	"\x0fOrderTypeCreate\x10\x01\x12\x14\n" +
	"\x10OrderTypeRefresh\x10\x022i\n" +
	"\rClientService\x12X\n" +
	"\vCreateOrder\x12\".vpns.Client.V1.CreateOrderRequest\x1a#.vpns.Client.V1.CreateOrderResponse\"\x00B-Z+github.com/zxcguldev/vpns-api/client;clientb\x06proto3"

var (
	file_client_v1_client_api_proto_rawDescOnce sync.Once
	file_client_v1_client_api_proto_rawDescData []byte
)

func file_client_v1_client_api_proto_rawDescGZIP() []byte {
	file_client_v1_client_api_proto_rawDescOnce.Do(func() {
		file_client_v1_client_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v1_client_api_proto_rawDesc), len(file_client_v1_client_api_proto_rawDesc)))
	})
	return file_client_v1_client_api_proto_rawDescData
}

var file_client_v1_client_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_v1_client_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_client_v1_client_api_proto_goTypes = []any{
	(OrderType)(0),              // 0: vpns.Client.V1.OrderType
	(*CreateOrderRequest)(nil),  // 1: vpns.Client.V1.CreateOrderRequest
	(*CreateOrderResponse)(nil), // 2: vpns.Client.V1.CreateOrderResponse
	(*Tariff)(nil),              // 3: vpns.Client.V1.Tariff
}
var file_client_v1_client_api_proto_depIdxs = []int32{
	0, // 0: vpns.Client.V1.CreateOrderRequest.OrderType:type_name -> vpns.Client.V1.OrderType
	1, // 1: vpns.Client.V1.ClientService.CreateOrder:input_type -> vpns.Client.V1.CreateOrderRequest
	2, // 2: vpns.Client.V1.ClientService.CreateOrder:output_type -> vpns.Client.V1.CreateOrderResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_client_v1_client_api_proto_init() }
func file_client_v1_client_api_proto_init() {
	if File_client_v1_client_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v1_client_api_proto_rawDesc), len(file_client_v1_client_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_v1_client_api_proto_goTypes,
		DependencyIndexes: file_client_v1_client_api_proto_depIdxs,
		EnumInfos:         file_client_v1_client_api_proto_enumTypes,
		MessageInfos:      file_client_v1_client_api_proto_msgTypes,
	}.Build()
	File_client_v1_client_api_proto = out.File
	file_client_v1_client_api_proto_goTypes = nil
	file_client_v1_client_api_proto_depIdxs = nil
}
