// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: client/v1/client_api.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderType int32

const (
	OrderType_OrderTypeUnspecified OrderType = 0
	OrderType_OrderTypeCreate      OrderType = 1
	OrderType_OrderTypeRefresh     OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "OrderTypeUnspecified",
		1: "OrderTypeCreate",
		2: "OrderTypeRefresh",
	}
	OrderType_value = map[string]int32{
		"OrderTypeUnspecified": 0,
		"OrderTypeCreate":      1,
		"OrderTypeRefresh":     2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v1_client_api_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_client_v1_client_api_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_client_v1_client_api_proto_rawDescGZIP(), []int{0}
}

type CreateOrderNewConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TariffID      int64                  `protobuf:"varint,1,opt,name=TariffID,proto3" json:"TariffID,omitempty"`
	ClientID      string                 `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderNewConfigRequest) Reset() {
	*x = CreateOrderNewConfigRequest{}
	mi := &file_client_v1_client_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderNewConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderNewConfigRequest) ProtoMessage() {}

func (x *CreateOrderNewConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderNewConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderNewConfigRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderNewConfigRequest) GetTariffID() int64 {
	if x != nil {
		return x.TariffID
	}
	return 0
}

func (x *CreateOrderNewConfigRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

type CreateOrderNewConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderNewConfigResponse) Reset() {
	*x = CreateOrderNewConfigResponse{}
	mi := &file_client_v1_client_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderNewConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderNewConfigResponse) ProtoMessage() {}

func (x *CreateOrderNewConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderNewConfigResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderNewConfigResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderNewConfigResponse) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

type CreateOrderRefreshConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TariffID      int64                  `protobuf:"varint,1,opt,name=TariffID,proto3" json:"TariffID,omitempty"`
	ConfigID      string                 `protobuf:"bytes,2,opt,name=ConfigID,proto3" json:"ConfigID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRefreshConfigRequest) Reset() {
	*x = CreateOrderRefreshConfigRequest{}
	mi := &file_client_v1_client_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRefreshConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRefreshConfigRequest) ProtoMessage() {}

func (x *CreateOrderRefreshConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRefreshConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRefreshConfigRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRefreshConfigRequest) GetTariffID() int64 {
	if x != nil {
		return x.TariffID
	}
	return 0
}

func (x *CreateOrderRefreshConfigRequest) GetConfigID() string {
	if x != nil {
		return x.ConfigID
	}
	return ""
}

type CreateOrderRefreshConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRefreshConfigResponse) Reset() {
	*x = CreateOrderRefreshConfigResponse{}
	mi := &file_client_v1_client_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRefreshConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRefreshConfigResponse) ProtoMessage() {}

func (x *CreateOrderRefreshConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRefreshConfigResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderRefreshConfigResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_api_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRefreshConfigResponse) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

type GetTariffsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTariffsRequest) Reset() {
	*x = GetTariffsRequest{}
	mi := &file_client_v1_client_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTariffsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTariffsRequest) ProtoMessage() {}

func (x *GetTariffsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTariffsRequest.ProtoReflect.Descriptor instead.
func (*GetTariffsRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_api_proto_rawDescGZIP(), []int{4}
}

type GetTariffsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Items         []*GetTariffsResponseItem `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTariffsResponse) Reset() {
	*x = GetTariffsResponse{}
	mi := &file_client_v1_client_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTariffsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTariffsResponse) ProtoMessage() {}

func (x *GetTariffsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTariffsResponse.ProtoReflect.Descriptor instead.
func (*GetTariffsResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetTariffsResponse) GetItems() []*GetTariffsResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetTariffsResponseItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Cost           string                 `protobuf:"bytes,3,opt,name=Cost,proto3" json:"Cost,omitempty"`
	SubDuration    *durationpb.Duration   `protobuf:"bytes,4,opt,name=SubDuration,proto3" json:"SubDuration,omitempty"`
	TariffType     OrderType              `protobuf:"varint,5,opt,name=TariffType,proto3,enum=vpns.Client.V1.OrderType" json:"TariffType,omitempty"`
	ConfigQuantity int64                  `protobuf:"varint,6,opt,name=ConfigQuantity,proto3" json:"ConfigQuantity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTariffsResponseItem) Reset() {
	*x = GetTariffsResponseItem{}
	mi := &file_client_v1_client_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTariffsResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTariffsResponseItem) ProtoMessage() {}

func (x *GetTariffsResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTariffsResponseItem.ProtoReflect.Descriptor instead.
func (*GetTariffsResponseItem) Descriptor() ([]byte, []int) {
	return file_client_v1_client_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetTariffsResponseItem) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GetTariffsResponseItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTariffsResponseItem) GetCost() string {
	if x != nil {
		return x.Cost
	}
	return ""
}

func (x *GetTariffsResponseItem) GetSubDuration() *durationpb.Duration {
	if x != nil {
		return x.SubDuration
	}
	return nil
}

func (x *GetTariffsResponseItem) GetTariffType() OrderType {
	if x != nil {
		return x.TariffType
	}
	return OrderType_OrderTypeUnspecified
}

func (x *GetTariffsResponseItem) GetConfigQuantity() int64 {
	if x != nil {
		return x.ConfigQuantity
	}
	return 0
}

var File_client_v1_client_api_proto protoreflect.FileDescriptor

const file_client_v1_client_api_proto_rawDesc = "" +
	"\n" +
	"\x1aclient/v1/client_api.proto\x12\x0evpns.Client.V1\x1a\x1egoogle/protobuf/duration.proto\"U\n" +
	"\x1bCreateOrderNewConfigRequest\x12\x1a\n" +
	"\bTariffID\x18\x01 \x01(\x03R\bTariffID\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID\"8\n" +
	"\x1cCreateOrderNewConfigResponse\x12\x18\n" +
	"\aOrderID\x18\x01 \x01(\tR\aOrderID\"Y\n" +
	"\x1fCreateOrderRefreshConfigRequest\x12\x1a\n" +
	"\bTariffID\x18\x01 \x01(\x03R\bTariffID\x12\x1a\n" +
	"\bConfigID\x18\x02 \x01(\tR\bConfigID\"<\n" +
	" CreateOrderRefreshConfigResponse\x12\x18\n" +
	"\aOrderID\x18\x01 \x01(\tR\aOrderID\"\x13\n" +
	"\x11GetTariffsRequest\"R\n" +
	"\x12GetTariffsResponse\x12<\n" +
	"\x05Items\x18\x01 \x03(\v2&.vpns.Client.V1.GetTariffsResponseItemR\x05Items\"\xf0\x01\n" +
	"\x16GetTariffsResponseItem\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Cost\x18\x03 \x01(\tR\x04Cost\x12;\n" +
	"\vSubDuration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vSubDuration\x129\n" +
	"\n" +
	"TariffType\x18\x05 \x01(\x0e2\x19.vpns.Client.V1.OrderTypeR\n" +
	"TariffType\x12&\n" +
	"\x0eConfigQuantity\x18\x06 \x01(\x03R\x0eConfigQuantity*P\n" +
	"\tOrderType\x12\x18\n" +
	"\x14OrderTypeUnspecified\x10\x00\x12\x13\n" +
	"\x0fOrderTypeCreate\x10\x01\x12\x14\n" +
	"\x10OrderTypeRefresh\x10\x022\xdc\x02\n" +
	"\rClientService\x12s\n" +
	"\x14CreateOrderNewConfig\x12+.vpns.Client.V1.CreateOrderNewConfigRequest\x1a,.vpns.Client.V1.CreateOrderNewConfigResponse\"\x00\x12\x7f\n" +
	"\x18CreateOrderRefreshConfig\x12/.vpns.Client.V1.CreateOrderRefreshConfigRequest\x1a0.vpns.Client.V1.CreateOrderRefreshConfigResponse\"\x00\x12U\n" +
	"\n" +
	"GetTariffs\x12!.vpns.Client.V1.GetTariffsRequest\x1a\".vpns.Client.V1.GetTariffsResponse\"\x00B-Z+github.com/zxcguldev/vpns-api/client;clientb\x06proto3"

var (
	file_client_v1_client_api_proto_rawDescOnce sync.Once
	file_client_v1_client_api_proto_rawDescData []byte
)

func file_client_v1_client_api_proto_rawDescGZIP() []byte {
	file_client_v1_client_api_proto_rawDescOnce.Do(func() {
		file_client_v1_client_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v1_client_api_proto_rawDesc), len(file_client_v1_client_api_proto_rawDesc)))
	})
	return file_client_v1_client_api_proto_rawDescData
}

var file_client_v1_client_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_v1_client_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_client_v1_client_api_proto_goTypes = []any{
	(OrderType)(0),                           // 0: vpns.Client.V1.OrderType
	(*CreateOrderNewConfigRequest)(nil),      // 1: vpns.Client.V1.CreateOrderNewConfigRequest
	(*CreateOrderNewConfigResponse)(nil),     // 2: vpns.Client.V1.CreateOrderNewConfigResponse
	(*CreateOrderRefreshConfigRequest)(nil),  // 3: vpns.Client.V1.CreateOrderRefreshConfigRequest
	(*CreateOrderRefreshConfigResponse)(nil), // 4: vpns.Client.V1.CreateOrderRefreshConfigResponse
	(*GetTariffsRequest)(nil),                // 5: vpns.Client.V1.GetTariffsRequest
	(*GetTariffsResponse)(nil),               // 6: vpns.Client.V1.GetTariffsResponse
	(*GetTariffsResponseItem)(nil),           // 7: vpns.Client.V1.GetTariffsResponseItem
	(*durationpb.Duration)(nil),              // 8: google.protobuf.Duration
}
var file_client_v1_client_api_proto_depIdxs = []int32{
	7, // 0: vpns.Client.V1.GetTariffsResponse.Items:type_name -> vpns.Client.V1.GetTariffsResponseItem
	8, // 1: vpns.Client.V1.GetTariffsResponseItem.SubDuration:type_name -> google.protobuf.Duration
	0, // 2: vpns.Client.V1.GetTariffsResponseItem.TariffType:type_name -> vpns.Client.V1.OrderType
	1, // 3: vpns.Client.V1.ClientService.CreateOrderNewConfig:input_type -> vpns.Client.V1.CreateOrderNewConfigRequest
	3, // 4: vpns.Client.V1.ClientService.CreateOrderRefreshConfig:input_type -> vpns.Client.V1.CreateOrderRefreshConfigRequest
	5, // 5: vpns.Client.V1.ClientService.GetTariffs:input_type -> vpns.Client.V1.GetTariffsRequest
	2, // 6: vpns.Client.V1.ClientService.CreateOrderNewConfig:output_type -> vpns.Client.V1.CreateOrderNewConfigResponse
	4, // 7: vpns.Client.V1.ClientService.CreateOrderRefreshConfig:output_type -> vpns.Client.V1.CreateOrderRefreshConfigResponse
	6, // 8: vpns.Client.V1.ClientService.GetTariffs:output_type -> vpns.Client.V1.GetTariffsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_client_v1_client_api_proto_init() }
func file_client_v1_client_api_proto_init() {
	if File_client_v1_client_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v1_client_api_proto_rawDesc), len(file_client_v1_client_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_v1_client_api_proto_goTypes,
		DependencyIndexes: file_client_v1_client_api_proto_depIdxs,
		EnumInfos:         file_client_v1_client_api_proto_enumTypes,
		MessageInfos:      file_client_v1_client_api_proto_msgTypes,
	}.Build()
	File_client_v1_client_api_proto = out.File
	file_client_v1_client_api_proto_goTypes = nil
	file_client_v1_client_api_proto_depIdxs = nil
}
