// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: integrator/v1/integrator_api.proto

package integrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_integrator_v1_integrator_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrator_v1_integrator_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_integrator_v1_integrator_api_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessPaymentRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_integrator_v1_integrator_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integrator_v1_integrator_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_integrator_v1_integrator_api_proto_rawDescGZIP(), []int{1}
}

var File_integrator_v1_integrator_api_proto protoreflect.FileDescriptor

const file_integrator_v1_integrator_api_proto_rawDesc = "" +
	"\n" +
	"\"integrator/v1/integrator_api.proto\x12\x0evpns.Client.V1\"1\n" +
	"\x15ProcessPaymentRequest\x12\x18\n" +
	"\aOrderID\x18\x01 \x01(\tR\aOrderID\"\x18\n" +
	"\x16ProcessPaymentResponse2t\n" +
	"\x11IntegratorService\x12_\n" +
	"\x0eProcessPayment\x12%.vpns.Client.V1.ProcessPaymentRequest\x1a&.vpns.Client.V1.ProcessPaymentResponseB5Z3github.com/zxcguldev/vpns-api/integrator;integratorb\x06proto3"

var (
	file_integrator_v1_integrator_api_proto_rawDescOnce sync.Once
	file_integrator_v1_integrator_api_proto_rawDescData []byte
)

func file_integrator_v1_integrator_api_proto_rawDescGZIP() []byte {
	file_integrator_v1_integrator_api_proto_rawDescOnce.Do(func() {
		file_integrator_v1_integrator_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_integrator_v1_integrator_api_proto_rawDesc), len(file_integrator_v1_integrator_api_proto_rawDesc)))
	})
	return file_integrator_v1_integrator_api_proto_rawDescData
}

var file_integrator_v1_integrator_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_integrator_v1_integrator_api_proto_goTypes = []any{
	(*ProcessPaymentRequest)(nil),  // 0: vpns.Client.V1.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil), // 1: vpns.Client.V1.ProcessPaymentResponse
}
var file_integrator_v1_integrator_api_proto_depIdxs = []int32{
	0, // 0: vpns.Client.V1.IntegratorService.ProcessPayment:input_type -> vpns.Client.V1.ProcessPaymentRequest
	1, // 1: vpns.Client.V1.IntegratorService.ProcessPayment:output_type -> vpns.Client.V1.ProcessPaymentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_integrator_v1_integrator_api_proto_init() }
func file_integrator_v1_integrator_api_proto_init() {
	if File_integrator_v1_integrator_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_integrator_v1_integrator_api_proto_rawDesc), len(file_integrator_v1_integrator_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_integrator_v1_integrator_api_proto_goTypes,
		DependencyIndexes: file_integrator_v1_integrator_api_proto_depIdxs,
		MessageInfos:      file_integrator_v1_integrator_api_proto_msgTypes,
	}.Build()
	File_integrator_v1_integrator_api_proto = out.File
	file_integrator_v1_integrator_api_proto_goTypes = nil
	file_integrator_v1_integrator_api_proto_depIdxs = nil
}
